<?php

namespace Tests\Unit;

use App\Models\Role;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use App\Models\Forum;

class PostTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testCreatePostWithMiddleware()
    {
        $data = [
            'title' => 'Post title for unit',
	        'body'  => '# Post body\n## This\n### Is\nFor\n- Unit\n- Testing'
        ];

        $forum = factory(Forum::class)->create();

        $this
            ->json('POST', '/api/forum/' . $forum['id'] . '/post', $data)
            ->assertStatus(401)
            ->assertJson(['message' => 'Unauthenticated.']);
    }

    public function  testCreatePostWithoutRoles() {
        $data = [
            'title' => 'Post title for unit',
            'body'  => '# Post body\n## This\n### Is\nFor\n- Unit\n- Testing'
        ];

        $forum = factory(Forum::class)->create();
        $user = factory(User::class)->create();

        $this
            ->actingAs($user, 'api')->json('POST', '/api/forum/' . $forum['id'] . '/post', $data)
            ->assertStatus(403)
            ->assertJson(['message' => 'You do not have the rights to perform this action']);
    }

    public function  testCreatePostWithRoles() {
        $data = [
            'title' => 'Post title for unit',
            'body'  => '# Post body\n## This\n### Is\nFor\n- Unit\n- Testing'
        ];

        $forum = factory(Forum::class)->create();
        $user = factory(User::class)->create();
        $role = factory(Role::class)->create();

        (new \App\Models\RolePerm)->create([
            'role_id' => $role['id'],
            'permission_id' => (new \App\Models\Permission())
                ->where('obj_id', '=', $forum['obj_id'])
                ->where('level', '=', 4)
                ->first()['id']
        ]);

        (new \App\Models\UserRole())->create([
            'role_id' => $role['id'],
            'user_id' => $user['id']
        ]);

        $this
            ->actingAs($user, 'api')->json('POST', '/api/forum/' . $forum['id'] . '/post', $data)
            ->assertStatus(201)
            ->assertJson([
                'message' => 'success',
                'post' => [
                    'title' => $data['title'],
                    'body' => $data['body'],
                    'forum_id' => $forum['id'],
                    'user_id' => $user['id'],
                ]
            ])
            ->assertJsonStructure(
                [
                    'message',
                    'post' => [
                        'title',
                        'body',
                        'forum_id',
                        'user_id',
                        'created_at',
                        'updated_at',
                        'id'
                    ]
                ]
            );
    }

    public function testGetAllPosts() {
        $forum = factory(Forum::class)->create();
        $user = factory(User::class)->create();
        $role = factory(Role::class)->create();

        (new \App\Models\RolePerm)->create([
            'role_id' => $role['id'],
            'permission_id' => (new \App\Models\Permission())
                ->where('obj_id', '=', $forum['obj_id'])
                ->where('level', '=', 2)
                ->first()['id']
        ]);

        (new \App\Models\UserRole())->create([
            'role_id' => $role['id'],
            'user_id' => $user['id']
        ]);

        $this
            ->actingAs($user, 'api')->json('GET', '/api/forum/' . $forum['id'] . '/posts')
            ->assertStatus(200)
            ->assertJson([
            'message' => 'success',
            ])
            ->assertJsonStructure(
                [
                    'message',
                    'posts' => [
                        'data' => [
                            [
                                'id',
                                'forum_id',
                                'user_id',
                                'title',
                                'body',
                                'created_at',
                                'updated_at',
                            ]
                        ],
                        'current_page',
                        'first_page_url',
                        'from',
                        'last_page',
                        'last_page_url',
                        'next_page_url',
                        'path',
                        'per_page',
                        'prev_page_url',
                        'to',
                        'total',
                    ]
                ]
            );
    }

    public function testUpdatePost() {
        $data = [
            'title' => 'Updated post title for unit',
            'body'  => '# Updated post body\n## This\n### Is\nFor\n- Unit\n- Testing'
        ];

        $forum = factory(Forum::class)->create();
        $user = factory(User::class)->create();
        $role = factory(Role::class)->create();

        $forum->posts()->create(['title' => 'hello', 'body' => 'hello again', 'user_id' => $user['id']]);

        (new \App\Models\RolePerm)->create([
            'role_id' => $role['id'],
            'permission_id' => (new \App\Models\Permission())
                ->where('obj_id', '=', $forum['obj_id'])
                ->where('level', '=', 2)
                ->first()['id']
        ]);

        (new \App\Models\UserRole())->create([
            'role_id' => $role['id'],
            'user_id' => $user['id']
        ]);

        $post = $this
            ->actingAs($user, 'api')->json('GET', '/api/forum/' . $forum['id'] . '/posts')
            ->assertStatus(200)
            ->decodeResponseJson()['posts']['data'][1];

        $this
            ->actingAs($user, 'api')->json('PATCH', '/api/forum/' . $forum['id'] . '/post/' . $post['id'], $data)
            ->assertStatus(200)
            ->assertJson([
                'message' => 'success',
                'post' => [
                    'title' => $data['title'],
                    'body' => $data['body'],
                    'forum_id' => $forum['id'],
                    'user_id' => $user['id'],
                ]
            ])
            ->assertJsonStructure(
                [
                    'message',
                    'post' => [
                        'title',
                        'body',
                        'forum_id',
                        'user_id',
                        'created_at',
                        'updated_at',
                        'id'
                    ]
                ]
            );
    }

    public function testDeletePost() {
        $data = [
            'title' => 'Updated post title for unit',
            'body'  => '# Updated post body\n## This\n### Is\nFor\n- Unit\n- Testing'
        ];

        $forum = factory(Forum::class)->create();
        $user = factory(User::class)->create();
        $role = factory(Role::class)->create();

        $forum
            ->posts()
            ->create(['title' => 'hello', 'body' => 'hello again', 'user_id' => $user['id']]);

        (new \App\Models\RolePerm)->create([
            'role_id' => $role['id'],
            'permission_id' => (new \App\Models\Permission())
                ->where('obj_id', '=', $forum['obj_id'])
                ->where('level', '=', 2)
                ->first()['id']
        ]);

        (new \App\Models\UserRole())->create([
            'role_id' => $role['id'],
            'user_id' => $user['id']
        ]);

        $post = $this
            ->actingAs($user, 'api')->json('GET', '/api/forum/' . $forum['id'] . '/posts')
            ->assertStatus(200)
            ->decodeResponseJson()['posts']['data'][1];

        $this
            ->actingAs($user, 'api')->json('DELETE', '/api/forum/' . $forum['id'] . '/post/' . $post['id'], $data)
            ->assertStatus(200)
            ->assertJson([
                'message' => 'success',
            ]);
    }
}
